# This workflow will check if the incoming pull request builds a valid documentation site

name: Validate site

on:
  pull_request:
    branches: [main, v*, archive]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: |
        npm i
        npm run-script check-links-local